title = "Projet ANR DT4CPS"
baseURL = "https://dt4cps.fr/"
languageCode = "fr-fr"
theme = "dt4cps"
resourceDir = "./resources"

DefaultContentLanguage = "fr"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
enableRobotsTXT = true

[taxonomies]
  labs = 'labs'
  tag = 'tags'

[languages]
  [languages.en]
    title = "Project ANR DT4CPS"
    weight = 2
    contentDir = "content/en"
    LanguageName = "English"
  [languages.fr]
    title = "Projet ANR DT4CPS"
    weight = 1
    contentDir = "content/fr"
    LanguageName = "Français"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/GoHugoIO"

 [module]
    [[module.mounts]]
      source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
      target = "assets/js/bootstrap.bundle.min.js"