#[[redirects]]
#    from = "/"
#    to = "/fr/"
#    force = true
#    conditions = { Language = ["fr"] }

#[[redirects]]
#    from = "/"
#    to = "/en/"
#    force = true
#    conditions = { Language = ["en"] }