[[redirects]]
    from = "/"
    to = "/fr/"
    status = 200
    force = true
    conditions = { Language = "fr" }

[[redirects]]
    from = "/"
    to = "/en/"
    status = 200
    force = true
    conditions = { Language = "en" }